// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wastelands.Service.Infrastructure;

#nullable disable

namespace Wastelands.Service.Infrastructure.Migrations
{
    [DbContext(typeof(WastelandsDbContext))]
    [Migration("20250320113905_AddStats")]
    partial class AddStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Cra")
                        .HasColumnType("integer")
                        .HasColumnName("Cra")
                        .HasComment("Craft");

                    b.Property<int>("Dex")
                        .HasColumnType("integer")
                        .HasColumnName("Dex")
                        .HasComment("Dexterity");

                    b.Property<int>("Emp")
                        .HasColumnType("integer")
                        .HasColumnName("Emp")
                        .HasComment("Empathy");

                    b.Property<int>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("Int")
                        .HasComment("Intellect");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Name");

                    b.Property<int>("Rea")
                        .HasColumnType("integer")
                        .HasColumnName("Rea")
                        .HasComment("Reaction");

                    b.Property<int>("Str")
                        .HasColumnType("integer")
                        .HasColumnName("Str")
                        .HasComment("Strength");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Wil")
                        .HasColumnType("integer")
                        .HasColumnName("Wil")
                        .HasComment("Willpower");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Character", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Character", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.User", null)
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
