// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wastelands.Service.Domain.Enums;
using Wastelands.Service.Infrastructure;

#nullable disable

namespace Wastelands.Service.Infrastructure.Migrations
{
    [DbContext(typeof(WastelandsDbContext))]
    [Migration("20260915134132_AddBodyAndCreatureTemplates")]
    partial class AddBodyAndCreatureTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BodyTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("GameId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("BodyTemplate", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BodyTemplatePart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BodyPartType")
                        .HasColumnType("integer")
                        .HasColumnName("BodyPartType");

                    b.Property<long>("BodyTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("BodyTemplateId");

                    b.Property<double>("DamageModifier")
                        .HasColumnType("double precision")
                        .HasColumnName("DamageModifier");

                    b.Property<int>("HitPenalty")
                        .HasColumnType("integer")
                        .HasColumnName("HitPenalty");

                    b.Property<int>("MaxToHit")
                        .HasColumnType("integer")
                        .HasColumnName("MaxToHit");

                    b.Property<int>("MinToHit")
                        .HasColumnType("integer")
                        .HasColumnName("MinToHit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("BodyTemplateId");

                    b.ToTable("BodyTemplatePart", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Cra")
                        .HasColumnType("integer")
                        .HasColumnName("Cra")
                        .HasComment("Craft");

                    b.Property<int>("Dex")
                        .HasColumnType("integer")
                        .HasColumnName("Dex")
                        .HasComment("Dexterity");

                    b.Property<int>("Emp")
                        .HasColumnType("integer")
                        .HasColumnName("Emp")
                        .HasComment("Empathy");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("Int")
                        .HasComment("Intellect");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Name");

                    b.Property<int>("Rea")
                        .HasColumnType("integer")
                        .HasColumnName("Rea")
                        .HasComment("Reaction");

                    b.Property<Dictionary<Skill, int>>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Skills")
                        .HasComment("Skills");

                    b.Property<int>("Str")
                        .HasColumnType("integer")
                        .HasColumnName("Str")
                        .HasComment("Strength");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Wil")
                        .HasColumnType("integer")
                        .HasColumnName("Wil")
                        .HasComment("Willpower");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Character", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.CreatureTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Body")
                        .HasColumnType("integer")
                        .HasColumnName("Body");

                    b.Property<long>("BodyTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("BodyTemplateId");

                    b.Property<int>("Cra")
                        .HasColumnType("integer")
                        .HasColumnName("Cra");

                    b.Property<int>("CreatureType")
                        .HasColumnType("integer")
                        .HasColumnName("CreatureType");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<int>("Dex")
                        .HasColumnType("integer")
                        .HasColumnName("Dex");

                    b.Property<int>("Emp")
                        .HasColumnType("integer")
                        .HasColumnName("Emp");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("GameId");

                    b.Property<int>("HP")
                        .HasColumnType("integer")
                        .HasColumnName("HP");

                    b.Property<int>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("Int");

                    b.Property<int>("Luck")
                        .HasColumnType("integer")
                        .HasColumnName("Luck");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("Ref")
                        .HasColumnType("integer")
                        .HasColumnName("Ref");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("Speed");

                    b.Property<int>("Sta")
                        .HasColumnType("integer")
                        .HasColumnName("Sta");

                    b.Property<int>("Will")
                        .HasColumnType("integer")
                        .HasColumnName("Will");

                    b.HasKey("Id");

                    b.ToTable("CreatureTemplate", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.CreatureTemplatePart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Armor")
                        .HasColumnType("integer")
                        .HasColumnName("Armor");

                    b.Property<int>("BodyPartType")
                        .HasColumnType("integer")
                        .HasColumnName("BodyPartType");

                    b.Property<long>("CreatureTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatureTemplateId");

                    b.Property<double>("DamageModifier")
                        .HasColumnType("double precision")
                        .HasColumnName("DamageModifier");

                    b.Property<int>("HitPenalty")
                        .HasColumnType("integer")
                        .HasColumnName("HitPenalty");

                    b.Property<int>("MaxToHit")
                        .HasColumnType("integer")
                        .HasColumnName("MaxToHit");

                    b.Property<int>("MinToHit")
                        .HasColumnType("integer")
                        .HasColumnName("MinToHit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CreatureTemplateId");

                    b.ToTable("CreatureTemplatePart", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedByUserId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.GameJoinRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("GameId");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("GameJoinRequest", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.UserGame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("GameId");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserGame", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BodyTemplatePart", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.BodyTemplate", null)
                        .WithMany("Parts")
                        .HasForeignKey("BodyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Character", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Game", null)
                        .WithMany("Characters")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wastelands.Service.Domain.Entities.User", null)
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.CreatureTemplatePart", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.CreatureTemplate", null)
                        .WithMany("Parts")
                        .HasForeignKey("CreatureTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BodyTemplate", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.CreatureTemplate", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Game", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
