// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wastelands.Service.Domain.Enums;
using Wastelands.Service.Infrastructure;

#nullable disable

namespace Wastelands.Service.Infrastructure.Migrations
{
    [DbContext(typeof(WastelandsDbContext))]
    [Migration("20260918153718_AddArmorTemplatesAndCombat")]
    partial class AddArmorTemplatesAndCombat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Ability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttackSkill")
                        .HasColumnType("integer")
                        .HasColumnName("AttackSkill");

                    b.Property<int>("AttacksPerTurn")
                        .HasColumnType("integer")
                        .HasColumnName("AttacksPerTurn");

                    b.Property<long?>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("CharacterId");

                    b.Property<long?>("CreatureTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatureTemplateId");

                    b.Property<int>("DamageDiceCount")
                        .HasColumnType("integer")
                        .HasColumnName("DamageDiceCount");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer")
                        .HasColumnName("DamageModifier");

                    b.Property<int>("DamageType")
                        .HasColumnType("integer")
                        .HasColumnName("DamageType");

                    b.Property<long?>("EquippedItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("EquippedItemId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CreatureTemplateId");

                    b.ToTable("Ability", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.AbilityAppliedCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AbilityId")
                        .HasColumnType("bigint")
                        .HasColumnName("AbilityId");

                    b.Property<int>("ApplyChance")
                        .HasColumnType("integer")
                        .HasColumnName("ApplyChance");

                    b.Property<int>("Condition")
                        .HasColumnType("integer")
                        .HasColumnName("Condition");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.ToTable("AbilityAppliedCondition", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.AbilityDefensiveSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AbilityId")
                        .HasColumnType("bigint")
                        .HasColumnName("AbilityId");

                    b.Property<int>("Skill")
                        .HasColumnType("integer")
                        .HasColumnName("Skill");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.ToTable("AbilityDefensiveSkill", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Battle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CurrentInitiative")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentInitiative");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentRound");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("GameId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Battle", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BattleAttack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AbilityId")
                        .HasColumnType("bigint")
                        .HasColumnName("AbilityId");

                    b.Property<int?>("AttackRoll")
                        .HasColumnType("integer")
                        .HasColumnName("AttackRoll");

                    b.Property<int>("AttackTotal")
                        .HasColumnType("integer");

                    b.Property<bool>("AttackerConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("AttackerConfirmed");

                    b.Property<long>("AttackerId")
                        .HasColumnType("bigint")
                        .HasColumnName("AttackerId");

                    b.Property<int>("AttackerKind")
                        .HasColumnType("integer")
                        .HasColumnName("AttackerKind");

                    b.Property<int>("AttacksAllowed")
                        .HasColumnType("integer")
                        .HasColumnName("AttacksAllowed");

                    b.Property<int>("AttacksUsed")
                        .HasColumnType("integer")
                        .HasColumnName("AttacksUsed");

                    b.Property<long>("BattleId")
                        .HasColumnType("bigint")
                        .HasColumnName("BattleId");

                    b.Property<int?>("DamageRoll")
                        .HasColumnType("integer")
                        .HasColumnName("DamageRoll");

                    b.Property<bool>("DefenderConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("DefenderConfirmed");

                    b.Property<long>("DefenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("DefenderId");

                    b.Property<int>("DefenderKind")
                        .HasColumnType("integer")
                        .HasColumnName("DefenderKind");

                    b.Property<int?>("DefenseRoll")
                        .HasColumnType("integer")
                        .HasColumnName("DefenseRoll");

                    b.Property<int>("DefenseTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("DefensiveSkill")
                        .HasColumnType("integer")
                        .HasColumnName("DefensiveSkill");

                    b.Property<bool?>("LastHitSucceeded")
                        .HasColumnType("boolean")
                        .HasColumnName("LastHitSucceeded");

                    b.Property<int>("Phase")
                        .HasColumnType("integer")
                        .HasColumnName("Phase");

                    b.Property<long?>("ResolvedCreaturePartId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResolvedCreaturePartId");

                    b.Property<int?>("ResolvedHumanBodyPart")
                        .HasColumnType("integer");

                    b.Property<long?>("TargetedCreaturePartId")
                        .HasColumnType("bigint")
                        .HasColumnName("TargetedCreaturePartId");

                    b.HasKey("Id");

                    b.HasIndex("BattleId")
                        .IsUnique();

                    b.ToTable("BattleAttack", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BattleCharacter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<string>("AppliedConditions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("AppliedConditions")
                        .HasComment("AppliedConditions");

                    b.Property<long>("BattleId")
                        .HasColumnType("bigint")
                        .HasColumnName("BattleId");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("CharacterId");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentHP");

                    b.Property<int>("CurrentSta")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentSta");

                    b.Property<int?>("Initiative")
                        .HasColumnType("integer")
                        .HasColumnName("Initiative");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer")
                        .HasColumnName("MaxHP");

                    b.Property<int>("MaxSta")
                        .HasColumnType("integer")
                        .HasColumnName("MaxSta");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("CharacterId");

                    b.ToTable("BattleCharacter", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BattleLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BattleId")
                        .HasColumnType("bigint")
                        .HasColumnName("BattleId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Message");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.ToTable("BattleLogEntry", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BodyTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("GameId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("BodyTemplate", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BodyTemplatePart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BodyPartType")
                        .HasColumnType("integer")
                        .HasColumnName("BodyPartType");

                    b.Property<long>("BodyTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("BodyTemplateId");

                    b.Property<double>("DamageModifier")
                        .HasColumnType("double precision")
                        .HasColumnName("DamageModifier");

                    b.Property<int>("HitPenalty")
                        .HasColumnType("integer")
                        .HasColumnName("HitPenalty");

                    b.Property<int>("MaxToHit")
                        .HasColumnType("integer")
                        .HasColumnName("MaxToHit");

                    b.Property<int>("MinToHit")
                        .HasColumnType("integer")
                        .HasColumnName("MinToHit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("BodyTemplateId");

                    b.ToTable("BodyTemplatePart", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Cra")
                        .HasColumnType("integer")
                        .HasColumnName("Cra")
                        .HasComment("Craft");

                    b.Property<int>("Dex")
                        .HasColumnType("integer")
                        .HasColumnName("Dex")
                        .HasComment("Dexterity");

                    b.Property<int>("Emp")
                        .HasColumnType("integer")
                        .HasColumnName("Emp")
                        .HasComment("Empathy");

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("HP")
                        .HasColumnType("integer")
                        .HasColumnName("HP");

                    b.Property<string>("ImageKey")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ImageKey");

                    b.Property<int>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("Int")
                        .HasComment("Intellect");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Name");

                    b.Property<int>("Rea")
                        .HasColumnType("integer")
                        .HasColumnName("Rea")
                        .HasComment("Reaction");

                    b.Property<Dictionary<Skill, int>>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Skills")
                        .HasComment("Skills");

                    b.Property<int>("Sta")
                        .HasColumnType("integer")
                        .HasColumnName("Sta");

                    b.Property<int>("Str")
                        .HasColumnType("integer")
                        .HasColumnName("Str")
                        .HasComment("Strength");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Wil")
                        .HasColumnType("integer")
                        .HasColumnName("Wil")
                        .HasComment("Willpower");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Character", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Creature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<string>("AppliedConditions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("AppliedConditions")
                        .HasComment("AppliedConditions");

                    b.Property<Dictionary<long, int>>("ArmorReductionByPartId")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ArmorReductionByPartId")
                        .HasDefaultValueSql("'{}'")
                        .HasComment("Износ брони по частям тела, накопленный этим существом в этом бою");

                    b.Property<long>("BattleId")
                        .HasColumnType("bigint")
                        .HasColumnName("BattleId");

                    b.Property<long>("CreatureTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatureTemplateId");

                    b.Property<int>("CreatureType")
                        .HasColumnType("integer")
                        .HasColumnName("CreatureType");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentHP");

                    b.Property<int>("CurrentSta")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentSta");

                    b.Property<int?>("Initiative")
                        .HasColumnType("integer")
                        .HasColumnName("Initiative");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer")
                        .HasColumnName("MaxHP");

                    b.Property<int>("MaxSta")
                        .HasColumnType("integer")
                        .HasColumnName("MaxSta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("Ref")
                        .HasColumnType("integer")
                        .HasColumnName("Ref");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.ToTable("Creature", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.CreatureTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Body")
                        .HasColumnType("integer")
                        .HasColumnName("Body");

                    b.Property<long>("BodyTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("BodyTemplateId");

                    b.Property<int>("Cra")
                        .HasColumnType("integer")
                        .HasColumnName("Cra");

                    b.Property<int>("CreatureType")
                        .HasColumnType("integer")
                        .HasColumnName("CreatureType");

                    b.Property<Dictionary<DamageType, DamageTypeModifier>>("DamageTypeModifiers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("DamageTypeModifiers")
                        .HasComment("DamageTypeModifiers");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<int>("Dex")
                        .HasColumnType("integer")
                        .HasColumnName("Dex");

                    b.Property<int>("Emp")
                        .HasColumnType("integer")
                        .HasColumnName("Emp");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("GameId");

                    b.Property<int>("HP")
                        .HasColumnType("integer")
                        .HasColumnName("HP");

                    b.Property<string>("ImageKey")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ImageKey");

                    b.Property<int>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("Int");

                    b.Property<int>("Luck")
                        .HasColumnType("integer")
                        .HasColumnName("Luck");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("Ref")
                        .HasColumnType("integer")
                        .HasColumnName("Ref");

                    b.Property<Dictionary<Skill, int>>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Skills")
                        .HasComment("Skills");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("Speed");

                    b.Property<int>("Sta")
                        .HasColumnType("integer")
                        .HasColumnName("Sta");

                    b.Property<int>("Will")
                        .HasColumnType("integer")
                        .HasColumnName("Will");

                    b.HasKey("Id");

                    b.HasIndex("BodyTemplateId");

                    b.HasIndex("GameId");

                    b.ToTable("CreatureTemplate", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.CreatureTemplatePart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Armor")
                        .HasColumnType("integer")
                        .HasColumnName("Armor");

                    b.Property<int>("BodyPartType")
                        .HasColumnType("integer")
                        .HasColumnName("BodyPartType");

                    b.Property<long>("CreatureTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatureTemplateId");

                    b.Property<double>("DamageModifier")
                        .HasColumnType("double precision")
                        .HasColumnName("DamageModifier");

                    b.Property<int>("HitPenalty")
                        .HasColumnType("integer")
                        .HasColumnName("HitPenalty");

                    b.Property<int>("MaxToHit")
                        .HasColumnType("integer")
                        .HasColumnName("MaxToHit");

                    b.Property<int>("MinToHit")
                        .HasColumnType("integer")
                        .HasColumnName("MinToHit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CreatureTemplateId");

                    b.ToTable("CreatureTemplatePart", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedByUserId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.GameJoinRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("GameId");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("GameJoinRequest", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AttackRange")
                        .HasColumnType("integer")
                        .HasColumnName("AttackRange");

                    b.Property<int?>("AttackSkill")
                        .HasColumnType("integer")
                        .HasColumnName("AttackSkill");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("CharacterId");

                    b.Property<int>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("Cost");

                    b.Property<int?>("DamageDiceCount")
                        .HasColumnType("integer")
                        .HasColumnName("DamageDiceCount");

                    b.Property<int?>("DamageModifier")
                        .HasColumnType("integer")
                        .HasColumnName("DamageModifier");

                    b.Property<int?>("DamageType")
                        .HasColumnType("integer")
                        .HasColumnName("DamageType");

                    b.Property<Dictionary<DamageType, DamageTypeModifier>>("DamageTypeModifiers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("DamageTypeModifiers")
                        .HasComment("DamageTypeModifiers");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<int?>("Durability")
                        .HasColumnType("integer")
                        .HasColumnName("Durability");

                    b.Property<int?>("HandsRequired")
                        .HasColumnType("integer")
                        .HasColumnName("HandsRequired");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean")
                        .HasColumnName("IsEquipped");

                    b.Property<bool?>("IsMultiAttack")
                        .HasColumnType("boolean")
                        .HasColumnName("IsMultiAttack");

                    b.Property<long>("ItemTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemTemplateId");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("ItemType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<int?>("WeaponKind")
                        .HasColumnType("integer")
                        .HasColumnName("WeaponKind");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("Weight");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.ItemAppliedCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplyChance")
                        .HasColumnType("integer");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemAppliedCondition");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.ItemArmorPart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ArmorValue")
                        .HasColumnType("integer")
                        .HasColumnName("ArmorValue");

                    b.Property<int>("CurrentDurability")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentDurability");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemId");

                    b.Property<int>("MaxDurability")
                        .HasColumnType("integer")
                        .HasColumnName("MaxDurability");

                    b.Property<int>("Part")
                        .HasColumnType("integer")
                        .HasColumnName("Part");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemArmorPart", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.ItemTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AttackRange")
                        .HasColumnType("integer")
                        .HasColumnName("AttackRange");

                    b.Property<int?>("AttackSkill")
                        .HasColumnType("integer")
                        .HasColumnName("AttackSkill");

                    b.Property<int>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("Cost");

                    b.Property<int?>("DamageDiceCount")
                        .HasColumnType("integer")
                        .HasColumnName("DamageDiceCount");

                    b.Property<int?>("DamageModifier")
                        .HasColumnType("integer")
                        .HasColumnName("DamageModifier");

                    b.Property<int?>("DamageType")
                        .HasColumnType("integer")
                        .HasColumnName("DamageType");

                    b.Property<Dictionary<DamageType, DamageTypeModifier>>("DamageTypeModifiers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("DamageTypeModifiers")
                        .HasComment("DamageTypeModifiers");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<int?>("Durability")
                        .HasColumnType("integer")
                        .HasColumnName("Durability");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("GameId");

                    b.Property<int?>("HandsRequired")
                        .HasColumnType("integer")
                        .HasColumnName("HandsRequired");

                    b.Property<bool?>("IsMultiAttack")
                        .HasColumnType("boolean")
                        .HasColumnName("IsMultiAttack");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("ItemType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<int?>("WeaponKind")
                        .HasColumnType("integer")
                        .HasColumnName("WeaponKind");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("Weight");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplate", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.ItemTemplateAppliedCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplyChance")
                        .HasColumnType("integer");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<long>("ItemTemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemTemplateId");

                    b.ToTable("ItemTemplateAppliedCondition");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.ItemTemplateArmorPart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ArmorValue")
                        .HasColumnType("integer")
                        .HasColumnName("ArmorValue");

                    b.Property<long>("ItemTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemTemplateId");

                    b.Property<int>("MaxDurability")
                        .HasColumnType("integer")
                        .HasColumnName("MaxDurability");

                    b.Property<int>("Part")
                        .HasColumnType("integer")
                        .HasColumnName("Part");

                    b.HasKey("Id");

                    b.HasIndex("ItemTemplateId");

                    b.ToTable("ItemTemplateArmorPart", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.UserGame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("GameId");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGame", (string)null);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Ability", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Character", null)
                        .WithMany("Abilities")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Wastelands.Service.Domain.Entities.CreatureTemplate", null)
                        .WithMany("Abilities")
                        .HasForeignKey("CreatureTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.AbilityAppliedCondition", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Ability", null)
                        .WithMany("AppliedConditions")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.AbilityDefensiveSkill", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Ability", null)
                        .WithMany("DefensiveSkills")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Battle", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Game", null)
                        .WithMany("Battles")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BattleAttack", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Battle", null)
                        .WithOne("Attack")
                        .HasForeignKey("Wastelands.Service.Domain.Entities.BattleAttack", "BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BattleCharacter", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Battle", null)
                        .WithMany("Characters")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wastelands.Service.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BattleLogEntry", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Battle", null)
                        .WithMany("LogEntries")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BodyTemplate", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Game", null)
                        .WithMany("BodyTemplates")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BodyTemplatePart", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.BodyTemplate", null)
                        .WithMany("Parts")
                        .HasForeignKey("BodyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Character", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Game", null)
                        .WithMany("Characters")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wastelands.Service.Domain.Entities.User", null)
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Creature", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Battle", null)
                        .WithMany("Creatures")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.CreatureTemplate", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.BodyTemplate", null)
                        .WithMany("CreatureTemplates")
                        .HasForeignKey("BodyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wastelands.Service.Domain.Entities.Game", null)
                        .WithMany("CreatureTemplates")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.CreatureTemplatePart", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.CreatureTemplate", null)
                        .WithMany("Parts")
                        .HasForeignKey("CreatureTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Game", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.User", null)
                        .WithMany("CreatedGames")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.GameJoinRequest", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Game", null)
                        .WithMany("GameJoinRequests")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wastelands.Service.Domain.Entities.User", null)
                        .WithMany("GameJoinRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Item", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Character", null)
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.ItemAppliedCondition", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Item", null)
                        .WithMany("AppliedConditions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.ItemArmorPart", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Item", null)
                        .WithMany("ArmorParts")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.ItemTemplateAppliedCondition", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.ItemTemplate", null)
                        .WithMany("AppliedConditions")
                        .HasForeignKey("ItemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.ItemTemplateArmorPart", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.ItemTemplate", null)
                        .WithMany("ArmorParts")
                        .HasForeignKey("ItemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.UserGame", b =>
                {
                    b.HasOne("Wastelands.Service.Domain.Entities.Game", null)
                        .WithMany("UserGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wastelands.Service.Domain.Entities.User", null)
                        .WithMany("UserGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Ability", b =>
                {
                    b.Navigation("AppliedConditions");

                    b.Navigation("DefensiveSkills");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Battle", b =>
                {
                    b.Navigation("Attack");

                    b.Navigation("Characters");

                    b.Navigation("Creatures");

                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.BodyTemplate", b =>
                {
                    b.Navigation("CreatureTemplates");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Character", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.CreatureTemplate", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Game", b =>
                {
                    b.Navigation("Battles");

                    b.Navigation("BodyTemplates");

                    b.Navigation("Characters");

                    b.Navigation("CreatureTemplates");

                    b.Navigation("GameJoinRequests");

                    b.Navigation("UserGames");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.Item", b =>
                {
                    b.Navigation("AppliedConditions");

                    b.Navigation("ArmorParts");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.ItemTemplate", b =>
                {
                    b.Navigation("AppliedConditions");

                    b.Navigation("ArmorParts");
                });

            modelBuilder.Entity("Wastelands.Service.Domain.Entities.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("CreatedGames");

                    b.Navigation("GameJoinRequests");

                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
